/* auto-generated by OHOS-RS */
/* eslint-disable */

import { NodeContent, UIContext } from '@kit.ArkUI';
export declare class MyApp {
  constructor(slot: NodeContent)
  createNativeNode(): void
  showDialog(): void
  createTextInput(): void
  animation(ctx: ArkUIContext): void
  destroyNativeNode(): void
  /**
    * A gallery page exercising more built-in components, gestures and
    * events: Button, Toggle, Slider, Progress, Checkbox, Radio, Swiper,
    * Stack, plus tap/pan/pinch/swipe/rotation gestures and hover/focus/
    * appear events.
    */
  createGallery(): void
}

