/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function capture(): string

export declare function lastResult(): string

export declare function sessionInfo(): string

export declare function switchFlash(on: boolean): string

