/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function drawXcomponent(): void

/** Constrain the expected frame rate range of the surface's frame callbacks. */
export declare function setFrameRate(min: number, max: number, expected: number): void

